parameters:
    igp.badges.subscriber.class: PROCERGS\LoginCidadao\IgpBundle\Event\BadgesSubscriber
    igp.validations.subscriber.class: PROCERGS\LoginCidadao\IgpBundle\Event\ValidationSubscriber

    igp.validations.rg.validator.class: PROCERGS\LoginCidadao\IgpBundle\Validator\Constraints\RGValidator

services:
    igp.badges.subscriber:
        class: %igp.badges.subscriber.class%
        arguments: [ @translator, @doctrine.orm.entity_manager ]
        tags:
            - { name: kernel.event_subscriber }

    igp.validations.subscriber:
        class: %igp.validations.subscriber.class%
        arguments: [ @translator, @doctrine.orm.entity_manager, @igp.validations.webservice ]
        tags:
            - { name: kernel.event_subscriber }

    igp.validations.webservice:
        class: PROCERGS\LoginCidadao\IgpBundle\Entity\IgpWs
        calls:
            - [setUrl, [%igp_ws_url%]]
            - [setUsername, [%igp_username%]]
            - [setPassword, [%igp_password%]]

    igp.validations.rg.validator:
        class: %igp.validations.rg.validator.class%
        arguments: [ @igp.validations.webservice ]
        tags:
            - { name: validator.constraint_validator, alias: igp_rg_validator }

    procergs_login_cidadao_igp.form.type.igpidcard:
        class: PROCERGS\LoginCidadao\IgpBundle\Form\IgpIdCardFormType
        tags:
            - { name: form.type, alias: lc_igpidcardformtype }
